name: Deploy

on:
  push:
    branches:
      - 'main'
jobs:
  DeployToPages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to pages
      run: npm run deploy